### ISSUE TITLE
How to configure commands such as "tab," "enter," and "ctrl/command + c"

### ISSUE THREAD

**Issue by jairaj0** [mauricedb/presentation-buddy#17]
I want to utilize this extension for a presentation, but I want to use emmets, which requires me to click the tab button; how can I accomplish this?

**Comment by mauricedb** [comment]
In general you want to execute the command that particular keypress triggers.

With Emmet you want to execute the `editor.emmet.action.expandAbbreviation` command.

So this `instructions.json` would work just fine:
```
[
  {
    "type": "createFile",
    "path": "src/demo.html"
  },
  {
    "type": "typeText",
    "text": ["ul.text-green-500>li#item$.m-4*5"]
  },
  {
    "type": "command",
    "command": "editor.emmet.action.expandAbbreviation"
  }
]
```

https://github.com/mauricedb/presentation-buddy/assets/3197730/7b6a74c2-86bc-4221-a778-6760da5c27fd
